name: BattleShops
version: 3.4.4
description: Complete shop system using remote chests and signs.

main: mc.alk.shops.bukkit.BukkitBattleShops

author: alkarin

softdepend: [Multiverse-Core, BattleCore]
depend: [Vault]

commands:
  shop:
    aliases:
    description: used to buy or sell multiples of the quantity listed
    usage: |
           /shop buy <multiple>x : Example /shop buy 64x : must be an integer >0 |
           /shop sell <multiple>x : Example /shop sell 64x : must be an integer >0 |
           /shop add <playername> : Add a player to your chest permissions |
           /shop remove <playername> : Remove a player to your chest permissions |
           /shop list : See who currently has permissions to your chests
  link:
    description: Link the item specified
    usage: |
           /link <item_name>
  unlink:
    description: Unlink the item specified
    usage: |
           /Unlink <item_name>
  shoptransactions:
    aliases: [shoptransaction,str]
    description: >
            Shows the transactions for a given shop
    usage: |
            /<command>  
  playertransactions:
    aliases: [playertransaction,ptr]
    description: >
             Shows the transactions for a given player
    usage: |
             /<command>

