version: 1.0

#intervalBetweenTransaction - How often can one person buy or sell to the shop? (In miliseconds: 1000ms = 1 sec)
intervalBetweenTransactions: 200

rightClickSignToOpenChest: false ## Currently disabled

## Whether or not shops are allowed across different worlds, or must be located in the same world
multiworld: true 

## The wand that players will use to link/unlink signs and chests
wand: 76 ## redstone torch

## Should players be allowed to break unprotected shop signs
# careful if set to false, players can make unbreakable shop signs in the wilderness
enableSignBreak: true

## which click buys/sells.. default is left click sells... right click buys
leftClickSells: true

## used on the first line to determine whether an admin shop is created. change for different languages
admin_string: admin 
admin_shop: "Admin Shop" ## What is the admin shop called on the sign

language: english ## which language to use in the messages.yml

SQLOptions:
  type: sqlite # sqlite or mysql
  db: minecraft # db name
  url : "localhost" # ignored if not mysql
  port : "3306" # ignored if not mysql
  username: "root"
  password: ""
 
 
